# Generated by Django 4.0.3 on 2022-04-18 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_app.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('STUDENT', 'Student'), ('LIBRARIAN', 'Librarian')], db_index=True, max_length=100)),
                ('department', models.CharField(choices=[('DANCE', 'Dance'), ('ECONOMICS', 'Economics'), ('ENGLISH', 'English'), ('PSYCHOLOGY', 'Psychology'), ('COMPUTER_SCIENCE', 'Computer Science'), ('POLITICAL_SCIENCE', 'Political Science'), ('STATISTICS', 'Statistics'), ('MATHEMATICS', 'Mathematics')], db_index=True, max_length=100)),
                ('study_level', models.CharField(choices=[('UNDERGRAD', 'Undergraduate'), ('GRAD', 'Graduate')], db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', library_app.manager.AppUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('total_copies', models.IntegerField(default=0)),
                ('copies_available_rent', models.IntegerField(default=0)),
                ('copies_available_sale', models.IntegerField(default=0)),
                ('fine', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=100)),
                ('request_for', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_book', to='library_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rented_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('fine', models.FloatField(default=0)),
                ('reserve_status', models.CharField(choices=[('OPEN', 'Open'), ('OVERDUE', 'Overdue'), ('CLOSE', 'Close')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_book', to='library_app.book')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserve',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='request',
            field=models.ManyToManyField(related_name='user_request', through='library_app.Request', to='library_app.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='reserve',
            field=models.ManyToManyField(related_name='user_reserve', through='library_app.Reserve', to='library_app.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
