# Generated by Django 4.0.3 on 2022-03-17 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request',
            field=models.ManyToManyField(related_name='user_request', through='library_app.Request', to='library_app.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='reserve',
            field=models.ManyToManyField(related_name='user_reserve', through='library_app.Reserve', to='library_app.book'),
        ),
        migrations.AlterField(
            model_name='request',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_book', to='library_app.book'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_book', to='library_app.book'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
