# Generated by Django 4.0.3 on 2022-04-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reserve',
        ),
        migrations.AddField(
            model_name='reserve',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
