# Generated by Django 3.2.13 on 2022-05-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_request_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('STUDENT', 'Student'), ('LIBRARIAN', 'Librarian'), ('EXTERNAL_USER', 'External User')], db_index=True, max_length=100),
        ),
    ]
